libpixelflinger: Avoid conflict symbols by hiding
prelink always complains conflict symbols:

ERROR: multiple definitions found for
[system/lib/libui.so:_ZN7android10VectorImpl13finish_vectorEv]!
        this definition     [system/lib/libpixelflinger.so]
        previous definition [system/lib/libutils.so]

The duplicated functions are found as following:

  $ arm-eabi-nm -C -D libutils.so | grep finish_vector
  0001d150 T android::VectorImpl::finish_vector()
  $ arm-eabi-nm -C -D libpixelflinger.so | grep finish_vector
  00014a44 T android::VectorImpl::finish_vector()

However, it is not allowed to link libutils into libpixelflinger, that
violates the layering of projects -- system/core can not depend on
frameworks/base.  This is the reason why some pieces of libutils were
duplicated into libpixelflinger in the first place.

To make prelink happy, this patch hides the conflict symbols by GCC
visibility.

Change-Id: I75af7e7f778c5b97d05e912206d24b1a9241dca3