Revert "audio: New audio formats for PCM Offload"
This reverts commit 0aaee68668358506c2aba9685707703dd6faba26.

This commit caused the following error:
system/core/include/system/audio.h: In function 'bool audio_is_valid_format(audio_format_t)':
system/core/include/system/audio.h:777:10: error: 'AUDIO_FORMAT_PCM_OFFLOAD' was not declared in this scope
system/core/include/system/audio.h:778:23: error: 'AUDIO_FORMAT_PCM_16_BIT_OFFLOAD' was not declared in this scope
system/core/include/system/audio.h:779:27: error: 'AUDIO_FORMAT_PCM_24_BIT_OFFLOAD' was not declared in this scope
make: *** [/home/bobzhome/android/system/out/target/product/p769/obj/SHARED_LIBRARIES/libnbaio_intermediates/AudioStreamInSource.o] Error 1

Change-Id: I68bccc2851e3820c7adb98af9e2e3818ea5bf01c