Update patch set 1
Patch Set 1:

I'm missing something?

system/core/healthd/healthd_mode_charger.cpp:611:59: error: 'healthd_board_mode_set_backlight' was not declared in this scope

Patch-set: 1
Reviewer: Arne Coucheron <444@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0