Update patch set 1
Patch Set 1:

Something is missing or wrong with my environment. The build succeeds, but adb fails to run:

adb devices
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
ADB server didn't ACK
* failed to start daemon *
error: cannot connect to daemon

Patch-set: 1