Update patch set 3
Patch Set 3:

This breaks my build with "../system/core/base/logging.cpp:119: undefined reference to `__android_log_buf_print' perhaps if you could mention how to find th fd leaking procedure then that particular one would be whitelisted in device tree

Patch-set: 3